homeassistant:
  name: resident Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 30
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  packages: !include_dir_named packages
  external_url: !secret external_url
  internal_url: !secret internal_url
  country: US

frontend:
  themes: !include_dir_merge_named themes

my:
alexa:
  smart_home:
    endpoint: https://api.amazonalexa.com/v3/events
    client_id: !secret alexa_client_id
    client_secret: !secret alexa_client_secret
    locale: en-US
    filter:
      include_entities: !include alexa_include_entities.yaml
    entity_config:
      group.fence_lights:
        name: Fence Lights
        description: Both fence lights
        display_categories: LIGHT
config:
person:
conversation:
history:
logbook:
sun:
wake_on_lan:
system_health:
mobile_app:
media_source:
logger:
  default: info
  logs:
    alexapy: debug
stream:

http:
  ip_ban_enabled: True
  login_attempts_threshold: -1
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.0.2.1/23
    - 192.0.2.1/24
    - 192.0.2.1/24

tts:
  - platform: google_translate
    language: en-uk
    service_name: google_say
    cache: true
  - platform: microsoft
    api_key: !secret ms_tts
    region: eastus
    language: en-us
    gender: Male
    type: en-US-GuyNeural
    cache: true

ifttt:
  key: !secret ifttt_password

timer:
  front_door_lights:
    duration: "00:03:00"

input_boolean:
  panic:
    name: Panic
    icon: mdi:alert-octagram-outline
  vestibule_light_triggered:
    name: vestibule_light_triggered
    initial: off
  toggle_spotify_av1:
    name: Toggle Spotify and AV1
    initial: off
  washer_was_running:
    name: Washer Was Running
    icon: mdi:washing-machine
  room_fun_tv_was_on:
    name: Room Fun TV Was On
    initial: off
  room_fun_active:
    name: Room Fun Active
    initial: off

group: !include_dir_merge_named groups
automation: !include_dir_list automation
sensor: !include_dir_merge_list sensors
media_player: !include_dir_merge_list media_player
switch: !include_dir_merge_list switches
alert: !include_dir_merge_named alerts
script: !include_dir_merge_named scripts/
notify: !include_dir_merge_list notify/
zone: !include_dir_merge_list zones/
mqtt:  !include mqtt/smart_switch.yaml
cloud: !include cloud.yaml
cover: !include_dir_merge_named cover
template: !include_dir_merge_list templates/
