homeassistant:
  name: Rodriguez Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 12
  unit_system: imperial
  time_zone: America/New_York
  #customize: !include customize.yaml
  #packages: !include_dir_named packages
  external_url: !secret external_url
  internal_url: !secret internal_url

frontend:
  themes: !include_dir_merge_named themes

alexa:
cloud: !include cloud.yaml
config:
mqtt:
person:
discovery:
conversation:
history:
logbook:
sun:
wake_on_lan:
system_health:
mobile_app:
media_extractor:
media_source:
logger:
  default: info
stream:

http:
  ip_ban_enabled: True
  login_attempts_threshold: 10
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.9
    - 172.30.33.8
    - 192.168.1.31

tts:
  - platform: google_translate
    service_name: google_say
    cache: true

weather:
  - platform: darksky
    api_key: !secret dark_sky_password
    mode: daily

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_password
  # "Project ID" in the Device Access Console
  project_id: !secret nest_project
  # Provide the full path exactly as shown under "Subscription name" in Google Cloud Console
  subscriber_id: !secret nest_subscriber

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:toggle-switch
    url: !secret tasmoadmin

ifttt:
  key: !secret ifttt_password

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

camera:
  - platform: generic
    still_image_url: "https://s.w-x.co/staticmaps/wu/wu/wxtype1200_cur/usbgm/animate.png"
    name: "NY Radar"

timer:
  front_door_lights:
    duration: "00:03:00"

input_boolean:
  panic:
    name: Panic
    icon: mdi:alert-octagram-outline

group: !include_dir_merge_named groups
automation: !include_dir_list automation
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
media_player: !include_dir_merge_list media_player
switch: !include_dir_merge_list switches
alert: !include_dir_merge_named alerts
script: !include_dir_merge_named scripts/
notify: !include_dir_merge_list notify/
zone: !include_dir_merge_list zones/
device_tracker: !include_dir_merge_list device_tracker/