homeassistant:
  name: Rodriguez Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 12
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

config:
updater:
person:
discovery:
conversation:
history:
logbook:
sun:
ios:
wink:
cloud:
wake_on_lan:
system_health:

switch:
  - platform: mqtt
    name: "Basement Fan"
    command_topic: "cmnd/sonoffS31-1/POWER"
    state_topic: "stat/sonoffS31-1/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

http:
  ip_ban_enabled: True
  login_attempts_threshold: 10
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# text to speech
tts:
  platform: google_translate

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_password

camera:
  - platform: ring

binary_sensor:
  - platform: ring
ring:
  username: !secret ring_username
  password: !secret ring_password

media_player:
  - platform: spotify
    client_id: !secret spotify_id
    client_secret: !secret spotify_secret
  - platform: plex
  - platform: yamaha
    host: 192.168.1.159
  - platform: kodi
    host: 192.168.1.214
    username: kodi
    password: !secret kodi_password

vacuum:
  - platform: roomba
    name: Rosie
    host: !secret roomba_host
    username: !secret roomba_blid
    password: !secret roomba_password

ifttt:
  key: !secret ifttt_password

notify:
  - name: Rodriguez_home_push_slack
    platform: slack
    api_key: !secret slack_api
    default_channel: !secret slack_chan

group: !include_dir_merge_named groups
automation: !include_dir_list automation
sensor: !include_dir_merge_list sensors/