homeassistant:
  name: Rodriguez Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 12
  unit_system: imperial
  time_zone: America/New_York
  #customize: !include customize.yaml
  packages: !include_dir_named packages
  external_url: !secret external_url

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

alexa:
config:
updater:
person:
discovery:
conversation:
history:
logbook:
sun:
wake_on_lan:
system_health:
mobile_app:
media_extractor:
logger:
  default: info

http:
  ip_ban_enabled: True
  login_attempts_threshold: 10

tts:
  platform: google_translate
  service_name: google_say
  cache: true

weather:
  - platform: darksky
    api_key: !secret dark_sky_password
    mode: daily

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_password

august:
  login_method: phone
  username: !secret august_username
  password: !secret august_password

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

ring:
  username: !secret ring_username
  password: !secret ring_password

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

vizio:
  - host: !secret ava_tv_ip
    access_token: !secret ava_tv_access
  - host: !secret aly_tv_ip
    access_token: !secret aly_tv_access
  - host: !secret ara_tv_ip
    access_token: !secret ara_tv_access

webostv:
    name: Living Room TV
    host: !secret livingroom_tv_ip
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret livingroom_tv_mac

roomba:
    host: !secret roomba_host
    blid: !secret roomba_blid
    password: !secret roomba_password

hue:
  bridges:
    - host: !secret hue_bridge
      allow_unreachable: true
      allow_hue_groups: true

velux:
  host: !secret velux_ip
  password: !secret velux_password

panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:toggle-switch
    url: !secret tasmoadmin

ifttt:
  key: !secret ifttt_password

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

camera:
  - platform: generic
    still_image_url: 'https://s.w-x.co/staticmaps/wu/wu/wxtype1200_cur/usbgm/animate.png'
    name: 'NY Radar'

group: !include_dir_merge_named groups
automation: !include_dir_list automation
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
media_player: !include_dir_merge_list media_player
switch: !include_dir_merge_list switches
alert: !include_dir_merge_named alerts
script: !include_dir_merge_named scripts/
notify: !include_dir_merge_list notify/
zone: !include_dir_merge_list zones/