- platform: history_stats
  name: Sprinkler ON today 5d
  unique_id: sprinkler_on_today_5d
  entity_id: switch.virtual_sprinkler
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: Sprinkler ON yesterday 5d
  unique_id: sprinkler_on_yesterday_5d
  entity_id: switch.virtual_sprinkler
  state: "on"
  type: time
  start: "{{ (now() - timedelta(days=1)).replace(hour=0, minute=0, second=0, microsecond=0) }}"
  end: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"

- platform: history_stats
  name: Sprinkler ON 2 days ago 5d
  unique_id: sprinkler_on_2_days_ago_5d
  entity_id: switch.virtual_sprinkler
  state: "on"
  type: time
  start: "{{ (now() - timedelta(days=2)).replace(hour=0, minute=0, second=0, microsecond=0) }}"
  end: "{{ (now() - timedelta(days=1)).replace(hour=0, minute=0, second=0, microsecond=0) }}"

- platform: history_stats
  name: Sprinkler ON 3 days ago 5d
  unique_id: sprinkler_on_3_days_ago_5d
  entity_id: switch.virtual_sprinkler
  state: "on"
  type: time
  start: "{{ (now() - timedelta(days=3)).replace(hour=0, minute=0, second=0, microsecond=0) }}"
  end: "{{ (now() - timedelta(days=2)).replace(hour=0, minute=0, second=0, microsecond=0) }}"

- platform: history_stats
  name: Sprinkler ON 4 days ago 5d
  unique_id: sprinkler_on_4_days_ago_5d
  entity_id: switch.virtual_sprinkler
  state: "on"
  type: time
  start: "{{ (now() - timedelta(days=4)).replace(hour=0, minute=0, second=0, microsecond=0) }}"
  end: "{{ (now() - timedelta(days=3)).replace(hour=0, minute=0, second=0, microsecond=0) }}"
