alias: "Aly Room Light Off"
trigger:
  platform: time
  at: '22:00:00'
condition:
  - condition: state
    entity_id: 'person.aly'
    state: 'away'
action:
  - service: light.turn_off
    entity_id: light.alys_room