alias: "Arabella Room Light Off"
trigger:
  platform: time
  at: '22:00:00'

condition:
  - condition: state
    entity_id: 'person.arabella'
    state: 'away'
  
action:
  - service: light.turn_off
    entity_id: light.arabellas_room
  - service: switch.turn_off
    entity_id: switch.sonoff1