trigger:
  platform: state
  entity_id: person.danielle
  from: "not_home"
  to: "home"
  for:
    seconds: 60 #"{{ states('input_number.lock_min')|int }}"
condition:
  condition: time
  before: '20:00:00'
  after: '17:00:00'
action:
  - service: notify.mobile_app_joerod_s_iphone
    data:
      message:
        Danielle is home.
  - delay: 00:00:05
  - service: tts.google_say
    entity_id: media_player.kitchen
    data_template:
      message: >-
        {{ [
        "Welcome home Mrs. Rodriguez. " ,
        "Hello Danielle. " ,
        "Hi Dani. " ,
        "Nice to see you back Danielle. " ,
        "Hi Danielle, looking gorgeous as always. "
        ] |random }}
  - service: tts.google_say
    entity_id: media_player.basement
    data:
      message: "Danielle is home"
alias: 'Welcome home Danielle'