alias: 'Turn On Office Light When Back Door is Open after Sunset.'
trigger:
  platform: state
  entity_id: binary_sensor.basement_door_contact
  from: 'off'
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: state
      entity_id: light.office
      state: 'off'
action:
  - service: sonos.snapshot
    continue_on_error: true
    target:
      entity_id: media_player.basement
    data:
      with_group: true

  - service: media_player.volume_set
    data:
      entity_id: media_player.basement
      volume_level: 0.7

  - service: light.turn_on
    data:
      entity_id: light.office
      brightness_pct: 100

  - service: notify.notify
    data:
      message: >-
        You came in through the basement and it was dark out, so I turned on the office light.
        Don't forget to lock the door and turn the office light off.

  - service: tts.google_say
    entity_id: media_player.basement
    data:
      message: >-
        {{ [
        "Don't forget to lock the door and turn off the office light.",
        "Let me get the light for you.",
        "Please remember to lock the basement door."
        ] | random }}

  - wait_template: "{{ not is_state('media_player.basement', 'playing') }}"
    timeout: '00:01:00'
    continue_on_timeout: true

  - service: sonos.restore
    continue_on_error: true
    target:
      entity_id: media_player.basement
    data:
      with_group: true
mode: single
