alias: 'Turn off basement fan when no one is around'
trigger:
  platform: state
  entity_id: person.joerod
  from: "home"
  to: "not_home"
  for:
    minutes: 10 #"{{ states('input_number.lock_min')|int }}"
condition:
  condition: state
  entity_id: switch.basement_fan
  state: 'on'
action:
  - service: switch.turn_off
    entity_id: switch.basement_fan
  - service: notify.mobile_app_joerod_s_iphone
    data:
      message:
        The basement fan has been turned off.