alias: "Christmas Tree Lights On"
trigger:
  - platform: time
    at: '15:00:00'
condition:
  - condition: state
    entity_id: automation.holiday_lights_on
    state: 'on'    
action:
  - service: light.turn_on
    data:
      entity_id: 
        - light.twinkly_37bdd1
  - service: switch.turn_on
    data:
      entity_id:
        - switch.drier      