alias: 'Turn on vestibule light when front door bell is pressed after sunset.'
trigger:
  platform: event
  event_type: nest_event
  event_data:
      device_id: a2546111bb8249995011ae373926226f
      type: doorbell_chime
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id:  light.vestibule
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: 'person.joe_rodriguez'
          state: 'home'
        - condition: state
          entity_id: 'person.danielle_rodriguez'
          state: 'home'
action:
  - service: light.turn_on
    data:
      entity_id: light.vestibule
      brightness_pct: 100
  - service: notify.mobile_app_joerod_s_iphone
    data:
      message:
        Someone is at the front door and it was dark out so I turned on the lights in the vestibule.  Don't forget to turn the vestibule light off.