alias: Doorbell Ring
trigger:
  platform: state
  entity_id: binary_sensor.front_door_ding
  from: "off"
  to: "on"
action:
- service: media_player.volume_set
  data:
    entity_id: media_player.living_room_tv
    volume_level: 0.1
- service: notify.living_room_tv
  data:
    message: "Someone's at the front Door"
- service: media_player.volume_set
  data:
    entity_id: media_player.kitchen_fire_tv
    volume_level: 0.1
- service: vacuum.pause
  data:
    entity_id: vacuum.rosie
- service: media_player.volume_set
  data:
    entity_id:
      - media_player.kitchen
      - media_player.basement
    volume_level: 0.80
- service: media_player.play_media
  data_template:
    entity_id:
      - media_player.kitchen
      - media_player.basement
    media_content_id: >
      {% if now().month == 10 and now().day > 7 -%}
        https://dl.dropboxusercontent.com/s/wyggy6lt680h8o2/Hedwigs%20Theme%20Bell.mp3?dl=0
      {% elif now().month == 12 %}
        https://dl.dropboxusercontent.com/s/bz7y7lj0o6bqaip/Christmas%20Bell.mp3?dl=0
      {% else %}
        https://dl.dropboxusercontent.com/s/whe4ee6mpzv2a5g/Jetsons.mp3?dl=0
      {%- endif %}
    media_content_type: music
- delay: 00:00:06
- service: tts.google_say
  entity_id:
    - media_player.kitchen
    - media_player.basement
  data_template:
    message: >-
      {{ [
      "Someone's at the front door. " ,
      "A visitor is at the front door. ",
      "A guest has arrived at the front door. "
      ] |random }}
- delay: 00:00:02
- service: media_player.volume_set
  data:
    entity_id:
      - media_player.kitchen
      - media_player.basement
    volume_level: 0.4
