alias: Doorbell Ring
trigger:
  platform: state
  entity_id: binary_sensor.front_door_ding
  from: "off"
  to: "on"
action:
- service: media_player.play_media
  data:
    entity_id:
      - media_player.basement
      - media_player.kitchen
    media_content_id: https://dl.dropboxusercontent.com/s/u4w8kp9iywibtxh/Door%20Bell%201.mp3?dl=0
    alias: Doorbell Ring
trigger:
  platform: state
  entity_id: binary_sensor.front_door_ding
  from: "off"
  to: "on"
action:
- service: media_player.volume_set
  data:
    entity_id: media_player.living_room_tv
    volume_level: 0.1
- service: media_player.volume_set
  data:
    entity_id: media_player.kitchen_fire_tv
    volume_level: 0.1
- service: vacuum.pause
  data:
    entity_id: vacuum.rosie
- service: media_player.volume_set
  data:
    entity_id:
      - media_player.basement
      - media_player.kitchen
    volume_level: 0.7
- service: media_player.play_media
  data:
    entity_id:
      - media_player.basement
      - media_player.kitchen
    media_content_id: /local/mp3/Door_Bell_4.mp3
    media_content_type: 'music'
- service: tts.google_say
  data:
    entity_id:
      - media_player.basement
      - media_player.kitchen
    data_template:
      message: >-
        {{ [
        "Someone's at the front door. " ,
        "A visitor is at the front door. ",
        "A guest has arrived"
        ] |random }}
- service: media_player.volume_set
  data:
    entity_id:
      - media_player.basement
      - media_player.kitchen
    volume_level: 0.4