alias: 'Turn on vestibule light when front door bell is pressed after sunset.'
trigger:
  platform: state
  entity_id:  binary_sensor.front_door_ding
  from: 'off'
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id:  light.vestibule
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: 'person.joerod'
          state: 'home'
        - condition: state
          entity_id: 'person.danielle'
          state: 'home'
action:
  - service: light.turn_on
    data:
      entity_id: light.vestibule
      brightness_pct: 100
  - service: notify.rodriguez_home_push_slack
    data:
      message:
        Someone is at the front door and it was dark out so I turned on the lights in the vestibule.  Don't forget to turn the vestibule light off.
  - service: tts.google_say
    entity_id: media_player.kitchen
    data_template:
      message: >-
        {{ [
        "Don't forget to lock the door and turn off the vestibule light. " ,
        "Please remember to lock the front door and turn off the vestibule light. "
        ] |random }}