alias: 'Turn On Vestibule Light When Front Door is Open after Sunset.'
trigger:
  platform: state
  entity_id: lock.front_door_lock
  to: 'unlocked'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: light.vestibule
      state: 'off'
action:
  - service: light.turn_on
    data:
      entity_id: light.vestibule
      brightness_pct: 100
  - service: notify.mobile_app_joerod_s_iphone
    data:
      message:
        You came in through the front door and it was dark out so I turned on the lights.  Don't forget to turn the vestibule light off.