alias: 'Hot day extra water'
trigger:
  platform: state
  entity_id: sensor.period_of_day
  to: 'dusk'
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.openweathermap_rain
      below: 0.1
    - condition: numeric_state
      entity_id: sensor.openweathermap_feels_like_temperature
      above: 50
    - condition: template
      value_template: "{% if now().month in [4,5,6,7,8,9] %}{{true}}{% else %}{{false}}{% endif %}"
    - condition: template
      value_template: "{{ states('sensor.max_temperature')|float >= 87.00 }}"
action:
  - service: switch.turn_on
    entity_id: switch.virtual_sprinkler
  - service: notify.notify
    data:
      message: >
        💦 Garden sprinkler has been turned on
        High for today - {{ states('sensor.openweathermap_feels_like_temperature') }}°
  - delay:
      minutes: 10
  - service: switch.turn_off
    entity_id: switch.virtual_sprinkler
  - service: notify.notify
    data:
      message: >
        💦 Garden sprinkler has been turned off.
mode: single
