alias: "🗑️ Garbage Day Reminder"
id: garbage_day_reminder
mode: single

trigger:
  - platform: time
    at: "20:30:00"

condition:
  - condition: time
    weekday:
      - sun
      - wed

  - condition: state
    entity_id: binary_sensor.sanitation_pickup_tomorrow
    state: "on"

action:
  - variables:
      weekday: "{{ now().isoweekday() }}"
      tts_message: >-
        {% if weekday == 7 %}
          Tomorrow is recycling, compost, and garbage collection. Don’t forget to put everything out tonight.
        {% elif weekday == 3 %}
          Tomorrow is bulk garbage collection only. Don’t forget to put out any large items tonight.
        {% else %}
          Garbage collection is tomorrow. Don’t forget to put it out tonight.
        {% endif %}

  - service: notify.notify
    data:
      title: "Garbage Day Reminder"
      message: "{{ tts_message }}"

  - service: sonos.snapshot
    continue_on_error: true
    target:
      entity_id:
        - media_player.kitchen
        - media_player.resident_twos_room
        - media_player.basement
        - media_player.main_bedroom
        - media_player.resident_threes_room
    data:
      with_group: true

  - service: tts.google_say
    data:
      entity_id: media_player.house_announcement_group
      message: "{{ tts_message }}"
      language: "en"

  - wait_template: >
      {{
        not is_state('media_player.kitchen', 'playing') and
        not is_state('media_player.resident_twos_room', 'playing') and
        not is_state('media_player.basement', 'playing') and
        not is_state('media_player.main_bedroom', 'playing') and
        not is_state('media_player.resident_threes_room', 'playing')
      }}
    timeout: '00:01:30'
    continue_on_timeout: true

  - service: sonos.restore
    continue_on_error: true
    target:
      entity_id:
        - media_player.kitchen
        - media_player.resident_twos_room
        - media_player.basement
        - media_player.main_bedroom
        - media_player.resident_threes_room
    data:
      with_group: true
