 # Turns on sprinkler off after a 10 minute water
alias: 'Garden Sprinkler Off'
trigger:
  platform: time
  at: 06:35:00
condition:
  condition: state
  entity_id: switch.garden_sprinkler
  state: 'on'
action:
  - service: switch.turn_off
    entity_id: switch.garden_sprinkler
  - service: notify.mobile_app_joerod_s_iphone
    data_template:
      message: >
        💦 Garden sprinkler has been turned off.
  - service: switch.turn_off
    entity_id: switch.garden_sprinkler
