# Turns on sprinkler if the probability of rain is below 35%
alias: 'Garden Sprinkler On'
trigger:
  platform: time
  at: '07:00:00'
condition:
  condition: numeric_state
  entity_id: sensor.dark_sky_precip_probability
  below: 35
action:
  - service: switch.turn_on
    entity_id: switch.garden_sprinkler
  - service: notify.rodriguez_home_push_slack
    data_template:
      message: >
        Garden sprinkler has been turned on.
        Chance of Rain - {{ states('sensor.dark_sky_precip_probability') }}