# this will anounce how far the bus is from my stop every weekday between 6:47AM - 7:10AM
alias: 'Get to the subway by bus'
trigger:
  platform: time_pattern
  minutes: "/3"
condition:
  condition: and
  conditions:
    - condition: time
      before: '07:10:00'
      after: '06:47:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: 'person.joerod'
      state: 'home'
    - condition: template
      value_template: >
        {% if states('calendar.joe_rodriguez') == 'on' and state_attr('calendar.joe_rodriguez', 'message') == "Day off" or state_attr('calendar.joe_rodriguez', 'message') == "WFH" -%}
          {{false}}
        {% else %}
          {{true}}
        {%- endif %}
action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.basement_sonos
      value: "{{ state_attr('media_player.basement', 'volume_level') | float}}"
  - service: input_number.set_value
    data_template:
      entity_id: input_number.kitchen_sonos
      value: "{{ state_attr('media_player.kitchen', 'volume_level') | float}}"
  - service: notify.mobile_app_joerod_s_iphone
    data:
      message:
        The bus is {{ ((as_timestamp(state_attr('sensor.home_to_subway', 'origin_stop_arrival_time'))-(as_timestamp(now()))) / 60)|int }} minutes away
  - service: media_player.volume_set
    data:
      entity_id:
        - media_player.basement
        - media_player.kitchen
      volume_level: 0.7
  - service: tts.google_say
    entity_id:
      - media_player.basement
      - media_player.kitchen
    data_template:
      message: >
        The bus is {{ ((as_timestamp(state_attr('sensor.home_to_subway', 'origin_stop_arrival_time'))-(as_timestamp(now()))) / 60)|int }} minutes away
  - delay: '00:00:10'
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.basement
      volume_level: "{{ states('input_number.basement_sonos') }}"
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.kitchen
      volume_level: "{{ states('input_number.kitchen_sonos') }}"