# this will announce how far the bus is from my stop every weekday between 6:47AM - 7:10AM
alias: 'Get to the subway by bus'
trigger:
  platform: time_pattern
  minutes: "/3"
condition:
  condition: and
  conditions:
    - condition: time
      before: '07:10:00'
      after: '06:47:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: person.resident_one
      state: 'home'
    - condition: template
      value_template: >
        {% set msg = (state_attr('calendar.resident_one', 'message') or '') | lower %}
        {% if states('calendar.resident_one') == 'on' and 'office' not in msg -%}
          {{ false }}
        {% else %}
          {{ true }}
        {%- endif %}
action:
  - service: notify.mobile_app_resident_one_s_iphone
    data:
      message: >-
        The bus is {{ states('sensor.1_dry_harbor_rd_63_av') | float(0) | round(0) | int }} minutes away

  - service: sonos.snapshot
    continue_on_error: true
    target:
      entity_id: media_player.basement
    data:
      with_group: true

  - service: media_player.volume_set
    data:
      entity_id: media_player.basement
      volume_level: 0.7

  - service: tts.google_say
    entity_id: media_player.basement
    data:
      message: >
        The bus is {{ states('sensor.1_dry_harbor_rd_63_av') | float(0) | round(0) | int }} minutes away

  - wait_template: "{{ not is_state('media_player.basement', 'playing') }}"
    timeout: '00:01:00'
    continue_on_timeout: true

  - service: sonos.restore
    continue_on_error: true
    target:
      entity_id: media_player.basement
    data:
      with_group: true
mode: single
