alias: "Holiday Lights On"
trigger:
  platform: numeric_state
  entity_id: sun.sun
  value_template: "{{ state_attr('sun.sun', 'elevation') }}"
  below: -2.5
action:
  - service: hue.hue_activate_scene
    data_template:
      group_name: "Garden"
      scene_name: >
        {% if is_state("calendar.holidays_in_united_states","on") -%}
          {% if state_attr('calendar.holidays_in_united_states','message') == "Valentine's Day" -%}
            Valentine's
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Presidents' Day (regional holiday)" %}
            USA
          {% elif state_attr('calendar.holidays_in_united_states','message') == "St. Patrick's Day" %}
            Jets
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Easter Sunday" %}
            Easter
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Mother's Day" %}
            Mother's Day
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Memorial Day" %}
            USA
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Independence Day" %}
            USA
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Halloween" %}
            Halloween
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Election Day" %}
            USA
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Labor Day" %}
            USA  
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Veterans Day" %}
            USA
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Thanksgiving Day" %}
            Fall
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Christmas Day" %}
            Christmas
          {% elif now().month == 10 and now().day > 7 %}
            Halloween   
          {% else %}
            Rodriguez Garden
          {%- endif %}
        {% elif now().month == 10 and now().day > 7 %}
          Halloween  
        {% elif now().month == 12 %}
          Christmas    
        {% else %}
          Rodriguez Garden
        {%- endif %}
  - service: hue.hue_activate_scene
    data_template:
      group_name: "Alys Room"
      scene_name: >
        {% if now().month == 10 and now().day > 7 -%}
        Halloween
        {% elif now().month == 12 and now().day > 7 %}                                                                                           
        Christmas
        {% else %}
        Alys Room
        {%- endif %}
  - service: switch.turn_on
    data:
      entity_id:
        - switch.side_door_light
        - switch.outdoor_switch
        - switch.sonoff1
        - switch.sonoff4
        - switch.sonoff5
  - service: light.turn_on
    data:
      entity_id:
        - light.arabella_s_night_light
