alias: 'Holiday front door motion lights On'
trigger:
  - platform: event
    event_type: nest_event
    event_data:
      device_id: a2546111bb8249995011ae373926226f
      type: camera_person
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: automation.holiday_lights_on
      state: 'on'
    - condition: numeric_state
      entity_id: sun.sun
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      below: -2.5
action:      
  - service: switch.turn_on
    data:   
      entity_id: 
        - switch.front_door_lights
  - service: timer.start
    target:
      entity_id: timer.front_door_lights