alias: "Holiday Lights On"
trigger:
  platform: numeric_state
  entity_id: sun.sun
  value_template: "{{ state_attr('sun.sun', 'elevation') }}"
  below: -2.25

action:
  - service: scene.turn_on
    target:
      entity_id: >
        {% if is_state("calendar.holidays_in_united_states","on") -%}
          {% if state_attr('calendar.holidays_in_united_states','message') == "Valentine's Day" -%}
            scene.valentines
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Presidents' Day (regional holiday)" %}
            scene.garden_usa
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Lunar New Year" %}
            scene.garden_red
          {% elif state_attr('calendar.holidays_in_united_states','message') == "St. Patrick's Day" %}
            scene.garden_st_patricks_day
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Easter Sunday" %}
            scene.easter
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Mother's Day" %}
            scene.mothers_day
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Memorial Day" %}
            scene.garden_usa
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Independence Day" %}
            scene.garden_usa
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Election Day" %}
            scene.garden_usa
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Labor Day" %}
            scene.garden_usa
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Veterans Day" %}
            scene.garden_usa
          {% elif state_attr('calendar.holidays_in_united_states','message') == "Thanksgiving Day" %}
            scene.garden_golden_star
          {% else %}
            scene.garden_resident_garden
          {%- endif %}
        {% elif now().month == 9 and now().day == 11 %}
          scene.garden_usa
        {% elif now().month == 10 and now().day > 2 %}
          scene.garden_halloween
        {% elif now().month == 7 and now().day < 5 and now().day > 1 %}
          scene.garden_usa
        {% elif (now().month == 11 and now().day > 28) or now().month == 12 %}
          scene.garden_christmas
        {% else %}
          scene.garden_resident_garden
        {%- endif %}

  - service: switch.turn_on
    data:
      entity_id:
        - switch.side_door_light
        - switch.font_door_lights
        - group.holiday_outside_lights
        - group.holiday_inside_lights
  - choose:
      - conditions: "{{ now().month == 12 }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.twinkly_37bdd1
