alias: Turn off Front Lights 3 minutes after last movement
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.front_door_lights
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: automation.holiday_lights_on
      state: 'on'
    - condition: state
      entity_id: switch.front_door_lights
      state: 'on'
action:
  service: switch.turn_off
  entity_id: switch.front_door_lights     