alias: 'Greet JoeRod'
trigger:
  platform: state
  entity_id: sensor.joerod_basement_beacon_distance
  from: "10"
  to: "0"
condition:
  condition: time
  after: '09:00:00'
  before: '22:00:00'

action:
  - service: tts.google_say
    entity_id: media_player.basement
    data_template:
      message: >-
        {{ [
        "Welcome back to the basement Joe!" ,
        "Hi handsome!",
        "Guess who's bizack."
        ] |random }}


        