alias: "Kids Lights Off - Bedtime"
trigger:
  platform: time
  at: '21:30:00'
action:
  - service: light.turn_off
    entity_id: light.ava_lamp
  - service: light.turn_off
    entity_id: light.ara_lightstrip
  - service: light.turn_off
    entity_id: light.aly_lightstrip