alias: "Kids Lights On - School"
trigger:
  - platform: time
    at: '08:30:00'
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{is_state_attr('binary_sensor.nyc311_school_exception_today', 'status', 'Open')}}"
    - condition: state
      entity_id: 'person.aly_rodriguez'
      state: 'home'    
action:
  - service: hue.hue_activate_scene
    data:
      group_name: "Alys Room"
      scene_name: "Read"
  - service: hue.hue_activate_scene
    data:
      group_name: "Arabellas Room"
      scene_name: "Read"
