alias: "Kids TV's Off - Bedtime"
trigger:
  platform: time
  at: '20:30:00'
condition:
  condition: time
  weekday:
      - sun
      - mon
      - tue
      - wed
      - thu
action:
  - service: media_player.turn_off
    entity_id: media_player.aly_s_tv
  - service: media_player.turn_off
    entity_id: media_player.arabella_s_tv