alias: "Kids Lights Off - Bedtime"
trigger:
  platform: time
  at: '21:30:00'
action:
  - service: light.turn_off
    entity_id: light.avas_room_lamp
  - service: light.turn_off
    entity_id: light.arabellas_hue_lightstrip_plus
  - service: light.turn_off
    entity_id: light.alyannas_hue_lightstrip_plus
