alias: "Kids TV's Off - Bedtime"
trigger:
  platform: time
  at: '21:00:00'
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
    - condition: template
      value_template: '{% if now().month in [7,8] %}{{false}}{% else %}{{true}}{% endif %}'
action:
  - service: media_player.turn_off
    entity_id: media_player.vizio_smartcast_aly
  - service: media_player.turn_off
    entity_id: media_player.vizio_smartcast_ara
  - service: media_player.turn_off
    entity_id: media_player.vizio_smartcast_ava