alias: 'Check when washing machine is done'
trigger:
  platform: numeric_state
  entity_id: sensor.current_power_usage_sonoffs31_2
  below: 5
  for:
    minutes: 5
condition:
  - condition: numeric_state
    entity_id: 'sensor.uptime'
    above: 8
action:
  - service: notify.all_notify
    data:
      message:
        🧺 The washing machine is done!
  - service: notify.living_room_tv
    data:
      message: "🧺 The washing machine is done!"
  - service: tts.google_say
    entity_id:
      - media_player.basement
      - media_player.kitchen
    data_template:
      message: >-
        {{ [
        "The washing machine is done!" ,
        "Looks like the load of clothes that are in the washing machine are done.",
        "Clear the washing machine before the clothes start to stink."
        ] |random }}
