alias: 'Check when dryer is done'
trigger:
  platform: numeric_state
  entity_id: sensor.current_power_usage_sonoffs31_3
  below: 5
  for:
    minutes: 5
condition:
  - condition: numeric_state
    entity_id: 'sensor.uptime'
    above: 8
action:
  - service: notify.all_notify
    data:
      message:
        🔥 The dryer is done!
  - service: notify.living_room_tv
    data:
      message: "🔥 The dryer is done!"
  - service: tts.google_say
    entity_id:
      - media_player.basement
      - media_player.kitchen
    data_template:
      message: >-
        {{ [
        "The dryer is done!" ,
        "Looks like the load of clothes that are in the dryer are done.",
        "Check the dryer, the dry cycle is complete.",
        "The dryer has stopped, you know how that goes, it may not be fully dry.  Check it out!"
        ] |random }}