alias: 'Sunset Outside Lights On'
trigger:
  platform: numeric_state
  entity_id: sun.sun
  value_template: "{{ state_attr('sun.sun', 'elevation') }}"
  below: -2.5
action:
  - service: hue.hue_activate_scene
    data:
      group_name: "Garden"
      scene_name: "Rodriguez Garden"
  - service: switch.turn_on
    entity_id: switch.front_door_lights
  - service: switch.turn_on
    entity_id: switch.side_door_light
  - service: switch.turn_on
    entity_id: switch.sonoff1