alias: 'Lock All Doors'
trigger:
  platform: state
  entity_id:  person.joerod, person.danielle
  from: "home"
  to: "not_home"
  for:
    minutes: 2 #"{{ states('input_number.lock_min')|int }}"
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: 'lock.front_door_lock'
      state: 'unlocked'
    - condition: state
      entity_id: 'lock.side_door'
      state: 'unlocked'
action:
  - service: lock.lock
    entity_id: lock.front_door_lock
  - service: lock.lock
    entity_id: lock.side_door
  - service: notify.rodriguez_home_push_slack
    data:
      message:
        All doors are locked.  You're safe!
  - service: tts.google_say
    entity_id: media_player.kitchen_sonos
    data_template:
      message: >-
        {{ [
        "All doors are locked.  You're safe!" ,
        "Someone left and didn't lock the doors, let me get that for you. "
        ] |random }}