alias: 'Main Bedroom Stop Cooling'
trigger:
  platform: template
  value_template: "{{ (states.climate.main_bedroom.attributes.current_temperature | float(0)) and (states.climate.main_bedroom.attributes.temperature | float(0)) and ( (states.climate.main_bedroom.attributes.current_temperature | float(0) - states.climate.main_bedroom.attributes.temperature | float(0)) | abs < 0.5 ) }}"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: 'person.resident_one'
      state: 'away'
action:
  - service: climate.turn_off
    entity_id: climate.main_bedroom
  - service: notify.notify
    data:
      message: >
        🛑 Main Bedroom Cooling Stopped.
        Main Bedroom Temperature - {{states.climate.main_bedroom.attributes.current_temperature}}°