alias: 'Office lights go on 100%'
trigger:
  platform: state
  entity_id: light.office_light
  to: "on"
condition:
  condition: template
  value_template:  "{{ state_attr('light.office_light', 'brightness') != 255 }}"
action:    
  - service: light.turn_on
    data:
      entity_id: light.office_light
      brightness_pct: 100