alias: 'Pool Filter'
trigger:
  - platform: time
    at: '07:00:00'
  - platform: time
    at: '19:30:00'
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.dark_sky_precip_probability
      below: 35
    - condition: template
      value_template: "{{states('sensor.pool_filter_on_today')|float * 60 < 300}}"  
action:
  - service: notify.mobile_app_joerod_s_iphone
    data_template:
      message: >
        {% if states('sensor.max_temperature')|float  >= 85.00 %}
        🏊 Pool filter has been turned on will run for 150 minutes.
        {% else %}
        🏊 Pool filter has been turned on will run for 90 minutes.
        {%- endif %}
        Chance of Rain - {{ states('sensor.dark_sky_precip_probability') }}%
  - service: switch.turn_on
    entity_id: switch.outdoor_switch
  - delay:
      minutes: > 
        {% if states('sensor.max_temperature')|float  >= 85.00 %}
          150
        {% else %}
          90
        {%- endif %}
  - service: switch.turn_off
    entity_id: switch.outdoor_switch
  - service: notify.mobile_app_joerod_s_iphone
    data_template:
      message: >
        🏊 Pool filter has been turned off.       