alias: 'Pool Filter Off'
trigger:
  - platform: time
    at: '07:45:00'
  - platform: time
    at: '14:45:00'
  - platform: time
    at: '17:45:00'
condition:
  condition: state
  entity_id: switch.outdoor_switch
  state: 'on'
action:
  - service: switch.turn_off
    entity_id: switch.outdoor_switch
  - service: notify.mobile_app_joerod_s_iphone
    data_template:
      message: >
        🏊 Pool filter has been turned off.