alias: 'Pool Filter On 5PM'
trigger:
  platform: time
  at: '17:00:00'
condition:
  condition: numeric_state
  entity_id: sensor.dark_sky_precip_probability
  below: 35
action:
  service: switch.turn_on
  entity_id: switch.pool_filter  
