alias: 'Pool Filter On'
trigger:
  - platform: time
    at: '07:00:00'
  - platform: time
    at: '12:00:00'
  - platform: time
    at: '17:00:00'
condition:
  condition: numeric_state
  entity_id: sensor.dark_sky_precip_probability
  below: 35
action:
  - service: switch.turn_on
    entity_id: switch.pool_filter
  - service: notify.rodriguez_home_push_slack
    data_template:
      message: >
        Pool filter has been turned on.
        Chance of Rain - {{ states('sensor.dark_sky_precip_probability') }}