alias: resident_two turns off AC when leaving
id: resident_two_turn_off_ac_when_leaving
mode: single

trigger:
  - platform: state
    entity_id: person.resident_two
    from: home
    to: not_home

condition:
  - condition: template
    value_template: "{{ not is_state('climate.resident_two', 'off') }}"

action:
  - service: climate.turn_off
    target:
      entity_id: climate.resident_two
