alias: "Rosey vacuums the first floor"
trigger:
  platform: time
  at: '09:30:00'
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: template
      value_template: >
        {% if states('calendar.deerodster_gmail_com') == 'on' and (state_attr('calendar.deerodster_gmail_com', 'message') | regex_match('clean|dina', ignorecase=true)) == 'True' -%}
         {{ false }}
        {% else %}
         {{ true }}
        {%- endif %}
    - condition: state
      entity_id: binary_sensor.rosey_bin_full
      state: 'off'
action:
  - service: vacuum.start
    entity_id: vacuum.rosey
  - service: notify.all_notify
    data_template:
      message:  >-
        {{ [
        "🧹 I'm going to vacuum the first floor" ,
        "🧹 Time to clean up all this cat hair.",
        "🧹 Time to earn my living."
        ] |random }}

  - service: tts.google_say
    entity_id: media_player.kitchen
    data_template:
      message: >-
        {{ [
        "I'm going to vacuum the first floor" ,
        "Time to clean up all this cat hair.",
        "Time to earn my living."
        ] |random }}