alias: "Rosie vacuums the first floor"
trigger:
  platform: time
  at: '09:00:00'
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ not is_state_attr('calendar.deerodster_gmail_com', 'message', 'Dina - House Cleaning') }}"
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.living_room_camera_motion_detected
          state: 'off'
        - condition: state
          entity_id: binary_sensor.living_room_camera_sound_detected
          state: 'off'
        - condition: template
          value_template: "{{ not is_state_attr('calendar.deerodster_gmail_com', 'message', 'Cleaning Lady') }}"
action:
  - service: vacuum.turn_on
    entity_id: vacuum.rosie
  - service: notify.rodriguez_home_push_slack
    data_template:
      message:  "I'm going to vacuum the 1st floor Mr. R"
  - service: tts.google_translate_say
    entity_id: media_player.kitchen
    data:
      message: "I'm going to vacuum the first floor"