alias: 'Turn On Side Door Light When Side Door is Open after Sunset.'
trigger:
  platform: state
  entity_id: binary_sensor.side_door_open
  from: 'off'
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id:  light.side_entrance
      state: 'off'
action:
  - service: light.turn_on
    data:
      entity_id: light.side_entrance
      brightness_pct: 100
  - service: notify.mobile_app_joerod_s_iphone
    data:
      message:
        You came in through the side door and it was dark out so I turned on the lights.  Don't forget to turn the side door light off.
  - service: tts.google_say
    entity_id: media_player.kitchen
    data_template:
      message: >-
        {{ [
        "Don't forget to lock the door and turn off the side door light. " ,
        "Please remember to lock the side door. "
        ] |random }}