alias: "Open Skylight Blind During the Day"
trigger:
  - platform: time
    at: '07:10:00'
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  #  - condition: state
  #    entity_id: person.danielle_rodriguez
  #    state: 'home'  
    - condition: template
      value_template: "{{ state_attr('calendar.deerodster_gmail_com','message') | regex_match('vacation', ignorecase=true) != True }}"
action:
  - service: cover.open_cover
    entity_id: cover.blind_1