alias: "Close Skylight Blind During the Day"
trigger:
  - platform: time
    at: '09:00:00'
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: template
      value_template: '{% if now().month in [5,6,7,8] %}{{false}}{% else %}{{true}}{% endif %}'
    - condition: state
      entity_id: person.danielle
      state: 'not_home'  
action:
  - service: cover.close_cover
    entity_id: cover.main_bedroom_blind
