alias: Home Panic Lights
trigger:
  platform: state
  entity_id: input_boolean.panic
  from: 'off'
  to: 'on'
action:
- alias: Repeat the sequence UNTIL the conditions are true
  repeat:
    sequence:
      - service: switch.toggle
        data:   
          entity_id:
            - switch.kitchen_light
            - switch.dining_room_light
      - delay: 00:00:01
    until:
      - condition: state
        entity_id: input_boolean.panic
        state: 'off'