alias: 'Sunrise Lights Off'
trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    above: -2.25
action:
  - service: light.turn_off
    target:
      entity_id:
        - light.garden
        - light.twinkly_37bdd1
  - service: switch.turn_off
    target:
      entity_id:
        - switch.font_door_lights
        - switch.side_door_light
        - group.holiday_outside_lights
        - group.holiday_inside_lights
  - service: cover.open_cover
    target:
      entity_id: cover.kitchen_blind
