alias: 'Sunrise Lights Off'
trigger:
  platform: numeric_state
  entity_id: sun.sun
  value_template: "{{ state_attr('sun.sun', 'elevation') }}"
  above: 1.5
action:
  - service: light.turn_off
    entity_id: light.garden
  - service: switch.turn_off
    entity_id: switch.front_lights
  - service: switch.turn_off
    entity_id: switch.side_door_light
  - service: light.turn_off
    entity_id: light.arabella_s_night_light
  - service: switch.turn_off
    entity_id: switch.holiday_lights
  - service: switch.turn_off
    entity_id: switch.basement_fan