alias: KLF reboot on hass stop event
description: ''
trigger:
  - event_data: {}
    event_type: homeassistant_stop
    platform: event
condition: []
action:
  - data: {}
    service: velux.reboot_gateway
mode: single