alias: Yard Camera Motion Sensor Lights On
trigger:
  platform: state
  entity_id: binary_sensor.backyard_camera_motion_detected
  to: 'on'
  for:
  minutes: 1
condition:
  condition: state
  entity_id: sun.sun
  state: 'below_horizon'
action:
  service: light.turn_on
  entity_id: switch.yard_fence_lights

alias: Yard Camera Motion Sensor Lights Off
trigger:
  - platform: state
    entity_id: binary_sensor.backyard_camera_motion_detected
    to: 'off'
    for:
      minutes: 2
action:
  - service: light.turn_off
    entity_id: switch.yard_fence_lights
