alias: Yard Camera Motion Sensor Lights On
trigger:
  platform: state
  entity_id: binary_sensor.backyard_camera_motion_detected
  to: 'on'
  for:
    seconds: 5
condition:
  condition: state
  entity_id: sun.sun
  state: 'below_horizon'
action:
  service: light.turn_on
  entity_id: switch.yard_fence_lights

