alias: Yard Camera Motion Sensor Lights Off
trigger:
  platform: state
  entity_id: binary_sensor.backyard_camera_person_detected
  to: 'off'
  for:
    seconds: 20
action:
  - service: switch.turn_off
    entity_id: switch.backyard_fence_lights